apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podrolebinding
subjects:
- kind: User
  name: user1 # name of your service account
roleRef: # referring to your Role
  kind: Role
  name: podrole
  apiGroup: rbac.authorization.k8s.io
