- hosts: all
  become: yes
  gather_facts: false
  
  tasks:
    - name: Install dependencies
      apt:
        name: {{ item }}
        state: present
        update_cache: yes  
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
    - name: Disable Swap
      shell: |
        swapoff -a
        
    - name: disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
        
    - name: Download Docker install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nyukeit/fixing-infra-op/main/install/installDocker.sh
        dest: /tmp
        mode: '0755'
        
    - name: Install Docker from script
      become: yes
      ansible.builtin.shell: bash /tmp/installDocker.sh
      
    - name: Restart Docker service
      become: yes
      ansible.builtin.systemd:
        state: restarted
        name: docker.service
        
    - name: Download CRI-Docker
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nyukeit/fixing-infra-op/main/install/installCRIDocker.sh
        dest: /tmp
        mode: '0755'
        
    - name: Install CRI-Docker
      ansible.builtin.shell: bash /tmp/installCRIDocker.sh
      
    - name: Restart CRI-Docker service
      ansible.builtin.systemd:
        state: restarted
        name: cri-docker.service
        
    - name: Download kubeadm, kubelet and kubectl install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nyukeit/fixing-infra-op/main/install/installK8S.sh
        dest: /tmp
        mode: '0755'
        
    - name: Install kubeadm, kubelet and kubectl
      ansible.builtin.shell: bash /tmp/installK8S.sh
