- hosts: master
  become: yes
  tasks:
    - name: Create empty file for kubeadm config
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no
        
    - name: Initialize the cluster (be patient!)
      shell: |
        kubeadm init --apiserver-advertise-address={{ hostvars['master'] }} --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock --ignore-preflight-errors=all
    
    - name: Create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
        
    - name: Copy admin.conf to user kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        
    - name: Install Pod Network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calico.yaml
